BankProject/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name = 'home'),
    path('index/', views.Index, name = 'index'),
    path('api/', include('api.urls', namespace = 'api'), name = 'api')
]

api/urls.py
from django.urls import path
from . import views

app_name = 'BankApp'

urlpatterns = [
   path('', views.Home, name = 'home'),
   path('branch/autocomplete/', views.AutoComplete, name= 'autocomplete'),
   path('branch/', views.Branch, name = 'branch'),
   path('autosuggest/', views.AutoSuggest, name = 'autosuggest'),
   path('banktable/', views.BankTable, name = 'banktable'),
   path('bankdetail/<int:pk>/', views.BankDetail, name='detail')

]

api/models.py
from django.shortcuts import reverse
from django.db import models

# Create your models here.


class BankParam(models.Model):
    ifsc = models.CharField(max_length = 11, null = False)
    bank_id = models.BigIntegerField()
    branch = models.CharField(max_length = 74)
    address = models.CharField(max_length = 195)
    city = models.CharField(max_length = 50)
    district = models.CharField(max_length = 50)
    state = models.CharField(max_length = 26)
    bank_name = models.CharField(max_length = 49)

    def __str__(self):
        return self.ifsc

    class Meta:
        ordering = ['ifsc']

BankProject/views.py
from django.shortcuts import render
from rest_framework.response import Response
from rest_framework.decorators import api_view
from django.views.decorators.cache import cache_page


def Index(request):
    return render(request, 'index.html')


@cache_page(60 * 60)
@api_view(['GET'])
def Home(request):
    context = {
      'Welcome' : 'Welcome to the Home Page. Down below are the end points for this app',
      'API application' : '/api/',
      'To search the bank detail by any of the fields' : '/api/branch/',
      'To search with branch name autosuggestion' : '/api/branch/autocomplete/',
      'To see all the bank list' : '/api/banktable/',
      'To directly see the bank detail (if you have a bank id)' : '/api/bankdetail/bankID/'
    }
    return Response(context)

api/views.py
from rest_framework.pagination import LimitOffsetPagination
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import cache_page
from django.http import JsonResponse,HttpResponse
from rest_framework.decorators import api_view
from rest_framework.response import Response
from .serializers import BankAppSerializer
from collections import defaultdict
from .models import BankParam
import json

# Create your views here.

total = len(BankParam.objects.all())


def Pagination(page):
   if page == None:
       return 0
   return int(page)

def Next(val):
    if val + 1 < total/10:
       val = val + 1
    else:
       val = total//10
    return val

def Previous(val):
    if not val - 1 < 0:
        val = val - 1
    return val


def LimitOffsetwithBank(request):
    q = request.GET.get("q")
    if q != None:
        result = list(BankParam.objects.filter(ifsc__icontains=q)) + list(BankParam.objects.filter(bank_id__icontains=q)) + list(BankParam.objects.filter(branch__icontains=q)) + list(BankParam.objects.filter(address__icontains=q)) + list(BankParam.objects.filter(city__icontains=q)) + list(BankParam.objects.filter(district__icontains=q)) + list(BankParam.objects.filter(state__icontains=q)) + list(BankParam.objects.filter(bank_name__icontains=q))
        return result[:10]
    else:
        return BankParam.objects.filter(bank_name__icontains="a")

def AutoSuggest(request):
    searchIt = request.GET.get("term")
    searchedResult = BankParam.objects.filter(branch__icontains = searchIt)
    result = [i.branch for i in searchedResult[:100]]
    return JsonResponse(result, safe=False)

@api_view(['GET'])
def BankTable(request):
    page = Pagination(request.GET.get("page"))
    if page > total:
        return Response('No page available!')
    list = BankParam.objects.all()[page*10:page*10+10]
    next = Next(page)
    previous = Previous(page)
    serializer = BankAppSerializer(list, many = True)
    dataJSON = json.dumps(serializer.data)
    context = {
     'data' : dataJSON,
     'list' : list,
     'next' : next,
     'previous' :previous,
    }
    return render(request, 'BankApp/banktable.html', context)


@api_view(['GET'])
@cache_page(60 * 60)
def Home(request):
    context = {
     'Welcome' : 'Welcome to the Home Page of API application. Down below are the end points for this app',
    'To search the bank detail by any of the fields' : '/branch/',
    'To search with branch name autosuggestion' : '/branch/autocomplete/',
    'To see all the bank list' : '/banktable/',
    'To directly see the bank detail (if you have a bank id)' : '/bankdetail/bankID/'
    }
    return Response(context)

@api_view(['GET'])
def Branch(request):
    display = []
    limit = request.GET.get("limit")
    offset = request.GET.get("offset")
    branch = LimitOffsetwithBank(request)
    if (limit == offset == None) or (limit == offset == ''):
        limit, offset = 10, 1
    elif (limit == None or limit == '') and (offset != None or offset != ''):
        limit = 1
    elif (limit != None or limit != '') and (offset == None or offset == ''):
        offset = 1
    for item in branch[int(offset)-1:int(offset)+int(limit)-1]:
        display.append(item)
    if request.GET.get("q") == None:
        return render(request, "BankApp/display.html")
    else:
        serializer = BankAppSerializer(display, many = True)
        return Response(serializer.data)


def AutoComplete(request):
    return render(request, "BankApp/autocomplete.html")

@cache_page(60 * 60)
@api_view(['GET'])
def BankDetail(request, pk):
    if pk > total:
        return Response('No branch available for this ID')
    bank = get_object_or_404(BankParam, pk=pk)
    return render(request, 'BankApp/bankdetail.html', {'detail' : bank})

api/templates/BankApp/autocomplete.html
{% include 'index.html' %}
{% block content %}
<div class="container headline">
  <p>SEARCH THE BANK DETAILS BY BRANCH NAME</p>
  <div class="jumbotron">
    <form action="{% url 'BankApp:branch' %}">
      <div class="decorate1">
        <input type="search" placeholder="search here" name="q" id="tags" >
        <input type="search" placeholder="limit" name="limit">
        <input type="search" placeholder="offset" name="offset">
      </div>
      <div class="decorate2">
        <button class="btn btn-primary" type="submit" name="button">Search</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

api/templates/BankApp/bankdetail.html
{% include 'index.html' %}
{% block content %}
<div class="jumbotron">
  <h6>Details of Bank  :: {{ detail.bank_name }}</h6>
  <table class="center">
    <tr class="big-info">
      <th>ID</th>
      <th>IFSC</th>
      <th>BANK ID</th>
      <th>BRANCH</th>
      <th>ADDRESS</th>
      <th>CITY</th>
      <th>DISTRICT</th>
      <th>STATE</th>
      <th>BANK NAME</th>
    </tr>
    <tbody id="detail">
      <tr>
        <td>{{ detail.id }}</td>
        <td>{{ detail.ifsc }}</td>
        <td>{{ detail.bank_id }}</td>
        <td>{{ detail.branch }}</td>
        <td>{{ detail.branch }}</td>
        <td>{{ detail.city }}</td>
        <td>{{ detail.district }}</td>
        <td>{{ detail.state }}</td>
        <td>{{ detail.bank_name }}</td>
      </tr>
    </tbody>
  </table>
</div>

{% endblock %}

api/templates/BankApp/banktable.html
{% include 'index.html' %}
{% block content %}
  <div class="pagination">
    <a class="btn btn-info" href="{% url 'BankApp:banktable' %}?page={{ previous }}"> previous</a>
    <a class="btn btn-info next" href="{% url 'BankApp:banktable' %}?page={{ next }}">next</a>
  </div>
  <div class="bar">
    <div class="dropdown">
        <button class="btn btn-info dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          City
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
           {% for i in list %}
            <a class="dropdown-item" href="{% url 'BankApp:detail' pk=i.id %}">{{ i.city }}</a>
           {% endfor %}
        </div>
    </div>
    <h6>To see the details of particular bank, please click on the respective row or click on City and choose the particular one</h6>
    <div class="bar1">
      <input type="search" placeholder="Search Here" id="searchInput">
      <form onsubmit="pageJumped()" action="{% url 'BankApp:banktable' %}" method="get">
        <input class="page" type="search" placeholder="page number" name="page">
      </form>
    </div>
  </div>
  <div class="table">
    <table class="center">
      <tr class="big-info">
        <th>ID</th>
        <th>IFSC</th>
        <th>BANK ID</th>
        <th>BRANCH</th>
        <th>ADDRESS</th>
        <th>CITY</th>
        <th>DISTRICT</th>
        <th>STATE</th>
        <th>BANK NAME</th> <hr>
      </tr>
      <tbody id="mytable">
      </tbody>
    </table>
   </div>

<script>
    function pageJumped() {
      alert("You are jumping to page number " + $('.page').val());
    }
    var data = JSON.parse("{{data|escapejs}}");
    buildTheTable(data)
    function buildTheTable(data) {
      var table = document.getElementById('mytable')
      table.innerHTML = ''
      for (var i = 0; i < data.length; i++){
        var row = `<tr class="clickme">
          <td id="me">${data[i].id}</td>
          <td>${data[i].ifsc}</td>
          <td>${data[i].bank_id}</td>
          <td>${data[i].branch}</td>
          <td>${data[i].address}</td>
          <td>${data[i].city}</td>
          <td>${data[i].district}</td>
          <td>${data[i].state}</td>
          <td>${data[i].bank_name}</td>
          </tr> <hr>`
        table.innerHTML += row

      }
   }


    var lst = document.querySelectorAll('.clickme')

    $('#searchInput').on('keyup', function(){
        var value = $(this).val();
        var newData = searchTable(value, data);
        buildTheTable(newData)
    })


   for (var i=0; i<lst.length; i++){
        lst[i].addEventListener("click", function() {
          var val = $(this).find("#me").html()
          callmeToSeeBankDetail(val);
        })
   }

   function callmeToSeeBankDetail(val){
      window.location = "{% url 'BankApp:detail' pk=1 %}".replace("1", val)
   }


  function searchTable(value, data){
    var newData = []

    for (var i = 0; i < data.length; i++){
      value = value.toLowerCase()
      var val1 = data[i].id.toString()
      var val2 = data[i].ifsc.toString().toLowerCase()
      var val3 = data[i].bank_id.toString()
      var val4 = data[i].branch.toLowerCase()
      var val5 = data[i].address.toLowerCase()
      var val6 = data[i].city.toLowerCase()
      var val7 = data[i].district.toLowerCase()
      var val8 = data[i].state.toLowerCase()
      var val9 = data[i].bank_name.toLowerCase()

      if (val1.includes(value) || val2.includes(value) || val3.includes(value) || val4.includes(value) || val5.includes(value) || val6.includes(value) || val7.includes(value) || val8.includes(value) || val8.includes(value) ) {
        newData.push(data[i])
      }
    }

    return newData
  }


</script>
{% endblock %}

api/templates/BankApp/display.html
{% include 'index.html' %}
{% block context %}
<div class="container headline">
    <p>SEARCH THE BANK DETAILS HERE</p>
    <div class="jumbotron">
    <form  method="get">
      <div class="decorate1">
        <input type="search" placeholder="Search Here" name="q">
        <input type="search" placeholder="limit" name="limit">
        <input type="search" placeholder="offset" name="offset">
      </div>
     <div class="decorate2">
      <button class="btn btn-info" type="submit">Search</button>
     </div>
    </form>
  </div>
</div>
{% endblock %}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Staatliches&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static '/css/style.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
  </head>
  <body>

  {% block content %}
  {% endblock %}
  {% include 'messages.html' %}
  {% block content2 %}
  {% endblock %}
  <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <script>
    $( function() {
      $( "#tags" ).autocomplete({
       source: "{% url 'BankApp:autosuggest' %}"
      });
     });
   </script>

</body>
</html>

templates/messages.html
{% if messages %}
  {% for message in messages %}
    {% if message.tags %}
      <div class= "{{ message.tags }} alert alert-info" role="alert">
        {{ message }}
      </div>
    {% endif %}
  {% endfor %}
{% endif %}